---
- name: arch-desk-setup
  hosts: all
  become: true

  roles:
    - role: packages # install pacman and paru packages
    - role: services # start services e.g. cups, ...
    - role: users # create a user
    - role: setup # other
    - role: filesystem # setup swap
    - role: dotfiles # deploy dotfiles
    - role: backup # rsync? over network with homeserver?
